# Generated by Django 5.1.4 on 2025-01-07 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('impact_sgds', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='notes_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Internet_Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('current_progress_description', models.TextField()),
                ('challenges_or_opportunities', models.TextField()),
                ('action_to_be_taken', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Key_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('I', 'In Progress')], default='P', max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_number', models.CharField(max_length=255)),
                ('team_leader', models.CharField(max_length=255)),
                ('project_locations', models.TextField()),
                ('donor', models.CharField(max_length=100)),
                ('budget', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('KES', 'Kenya Shillings'), ('UGX', 'Uganda Shillings'), ('USD', 'US Dollars')], default='USD', max_length=100)),
                ('implementing_partners', models.TextField()),
                ('beneficiaries', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_key_data', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='impact_sdgs',
            field=models.ManyToManyField(blank=True, to='projects.sdg'),
        ),
    ]
